[build]
command = "pnpm run build && pnpm run build"
publish = "dist"

[[headers]]
for = "/*"
[headers.values]
Referrer-Policy = "no-referrer"
Permissions-Policy = ""
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
