export const defaultLocale = 'en';

export const messages = {
	de: {
		back: 'Bring mich zurück.',
		hello: 'Hallo!',
		not_found: 'Oh je, diese Seite existiert nicht.',
		present: 'jetzt',
		resume: 'Lebenslauf',
		section_experiences: 'Berufserfahrung',
		section_interests: 'Interessen und Aktivitäten',
		section_languages: 'Sprachen',
		section_projects: 'Persönliche Projekte',
		section_skills: 'Erworbene Fähigkeiten',
		section_technologies: 'Vertraute Technologien',
		section_values: 'Persönliche Werte',
		site_description: 'Lebenslauf von Thomas Deinhamer, Frontend Entwickler aus Salzburg, Österreich.',
		site_title: 'Lebenslauf · Thomas Deinhamer',
		status: 'Ich bin offen für neue berufliche Perspektiven und spannende Herausforderungen.',
		touch: 'kontaktieren',
		undefined: 'undefiniert',
		who: 'Ich bin ein Frontend Entwickler aus Salzburg und liebe es, Dinge zu bauen.',
	},
	en: {
		back: 'Bring me home.',
		hello: 'Hello!',
		not_found: "Oops, this page doesn't exist.",
		present: 'present',
		resume: 'Resume',
		section_experiences: 'Work Experience',
		section_interests: 'Interests and Activities',
		section_languages: 'Languages',
		section_projects: 'Personal Projects',
		section_skills: 'Acquired Skills',
		section_technologies: 'Familiar Technologies',
		section_values: 'Personal Values',
		site_description: 'Resume of Thomas Deinhamer, frontend engineer from Salzburg, Austria.',
		site_title: 'Resume · Thomas Deinhamer',
		status: "I'm seeking new career opportunities to take on new challenges.",
		touch: 'Get in touch.',
		undefined: 'undefined',
		who: "I'm a Frontend Engineer from Salzburg, and I love building things.",
	},
};
