export const defaultLocale = 'en';

export const messages = {
	de: {
		back: 'Bring mich zurück.',
		change_locale: 'Englischsprachige Version',
		download_resume: 'Lebenslauf als PDF Dokument herunterladen',
		filename: 'lebenslauf-deinhamer.pdf',
		hello: 'Hallo!',
		link_bluesky: 'Bluesky Profil öffnen',
		link_github: 'GitHub Profil öffnen',
		link_linkedin: 'LinkedIn Profil öffnen',
		link_stack_overflow: 'Stack Overflow Profil öffnen',
		link_xing: 'Xing Profil öffnen',
		not_found: 'Oh je, diese Seite existiert nicht.',
		portrait: 'Porträt von Thomas Deinhamer',
		present: 'jetzt',
		resume: 'Lebenslauf',
		section_experiences: 'Berufliche Erfahrung',
		section_interests: 'Interessen',
		section_languages: 'Sprachen',
		section_projects: 'Persönliche Projekte',
		section_skills: 'Erworbene Fähigkeiten',
		section_technologies: 'Vertraute Technologien',
		section_values: 'Persönliche Werte',
		site_description: 'Lebenslauf von Thomas Deinhamer, Frontend Entwickler aus Salzburg, Österreich.',
		site_title: 'Lebenslauf · Thomas Deinhamer',
		status: 'Ich bin offen für neue berufliche Perspektiven und spannende Herausforderungen.',
		switch_theme: 'Farbschema wechseln',
		toggle_details: 'Details ein-/ausblenden',
		top: 'Nach oben scrollen',
		touch: 'kontaktieren',
		undefined: 'undefiniert',
		who: 'Ich bin ein Frontend Entwickler aus Salzburg und liebe es, Dinge zu bauen.',
		testimonial: 'Dienstzeugnis',
	},
	en: {
		back: 'Bring me home.',
		change_locale: 'Deutschsprachige Version',
		download_resume: 'Download resume as PDF document',
		filename: 'resume-deinhamer.pdf',
		hello: 'Hello!',
		link_bluesky: 'Open Bluesky profile',
		link_github: 'Open GitHub profile',
		link_linkedin: 'Open LinkedIn profile',
		link_stack_overflow: 'Open Stack Overflow profile',
		link_xing: 'Open Xing profile',
		not_found: 'Oops, this page doesn\'t exist.',
		portrait: 'Portrait of Thomas Deinhamer',
		present: 'present',
		resume: 'Resume',
		section_experiences: 'Professional Experience',
		section_interests: 'Interests and Activities',
		section_languages: 'Languages',
		section_projects: 'Personal Projects',
		section_skills: 'Acquired Skills',
		section_technologies: 'Familiar Technologies',
		section_values: 'Personal Values',
		site_description: 'Resume of Thomas Deinhamer, frontend engineer from Salzburg, Austria.',
		site_title: 'Resume · Thomas Deinhamer',
		status: 'I\'m seeking new career opportunities to take on new challenges.',
		switch_theme: 'Switch color theme',
		toggle_details: 'Toggle details',
		top: 'Scroll to top',
		touch: 'Get in touch.',
		undefined: 'undefined',
		who: 'I\'m a Frontend Engineer from Salzburg, and I love building things.',
		testimonial: 'Employment Reference Letter',
	},
};
